#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: Server Khalilov | CV
url: 'https://serverkhalilov.com'
baseurl: '' #change it according to your repository name
repository: 'red17electro/online-cv'
description: A beautiful Jekyll theme for creating resume
# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: ceramic # blue turquoise green berry orange ceramic teal oceanstale
chrome_mobile_color: #use hex colors (ex:#1976d2) or leave empty if you don't want a color for chrome mobile searchbar

# Tracker
# TODO: Migrate to Google Analytics 4 - Get your GA4 measurement ID from https://analytics.google.com/
analytics: G-M4Z3LLFBHD

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: localhost
safe: false
